### ISSUE TITLE
Add ARC weak proprety support to the runtime

### ISSUE THREAD

**Issue by jy** [Midar/objfw#11]
Would be great to have zeroing weak references. Any plans to add this?

**Comment by Midar** [comment]
I looked into this in the past, but somehow forgot about it again since I personally don't use ARC ;). If there's demand, I might as well increase the priority.

**Comment by dangerbird2** [comment]
Sorry if I'm bumping this feature request, but Microsoft has just released an open source Objective-C SDK, notably [using parts of ObjFW for its object runtime.](https://github.com/Microsoft/WinObjC/tree/master/Frameworks/objcrt). It looks like they're using garbage collection for automatic memory management right now, but it might be worth seeing if or how they develop ARC features as reference.

**Comment by Midar** [comment]
I'm not sure if they are ever going the ARC route, as this could complicate things for their bridge. However, ObjFW already *has* ARC support, the only thing that's missing is weak ARC. I'm currently preparing to release 0.8, and thus won't add any new features. But after that, it's on my priority list.

**Comment by Midar** [comment]
I finally remembered that I wanted to implement zeroing weak references and finally implemented it. Please test it (the more complex scenarious, the better!) and let me know if you encounter any problems.
