### ISSUE TITLE
KernelEventObserver (select) throws OutOfRangeException in random time when remove objects observed for reading

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#15]
I use async accept and async read methods in main run loop of my tcp server application. For automatic of clients disconnection I use OFTimer object with 10 sec. timeout, that execute cancelAsync Requests method for every connected socket. For testing server, I use python script, that connect to my server in loop, sends some data and disconnects. On server side, connection timeout timer closes socket connection automatically.
In some moment, after 70 - 80 connections, my TCP server falls with exception, when OFKernelEventObserver_select execute method OF_removeObjectForReading.
In source code I see checking "if (fd < 0 || fd >= FD_SETSIZE) @throw [OFOutOfRangeException exception];" (by default FD_SETSIZE == 1024), but in method OF_addObjectForReading, for Windows OS used "if (fd < 0 || fd > INT_MAX - 1) @throw [OFOutOfRangeException exception];"

My question is - How can I fix this incorrect (IMHO) behaviour?

(OS Windows 8.1 x86_64 + ObjFW DLL x86 (32-bit))

**Comment by Midar** [comment]
Thanks for spotting and reporting! FD_SETSIZE is broken on Windows, which is why I added #ifdefs to not use it on Windows. However, I seem to have forgotten two spots. This is fixed in master and the 0.8 branch now.
