### ISSUE TITLE
OFHTTPClient::performRequest:redirects: rewrite Multiple Set-Cookie headers in HTTP Response

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#18]
After parsing http response header, method use [serverHeaders setObject: value forKey: key]; to store key and value for every field in header, if HTTP server send response with multiple Set-Cookie fields, OFHTTPResponse save only last of them.
[2015-10-29 03:11:04.560 client.exe(30220)] Response on <OFHTTPRequest:
        URL = <OFURL: http://localhost/testcookie.php>
        Method = GET
        Headers = (nil)
        Body = (nil)
        Remote address = (nil)
> from server with status code 200 headers {
        Date = Thu, 29 Oct 2015 00:11:04 GMT;
        X-Powered-By = PHP/5.5.12;
        Set-Cookie = TestCookie=%F7%F2%EE-%F2%EE+%E3%E4%E5-%F2%EE; expires=Thu, 29-Oct-2015 01:11:04 GMT; Max-Age=3600; path=/~rasmus/; domain=example.com; secure;
        Content-Type = text/html;
        Server = Apache/2.4.9 (Win32) mod_fcgid/2.3.9 PHP/5.5.12;
        Content-Length = 21;
}
[2015-10-29 03:11:04.563 client.exe(30220)] Cookies: TestCookie=%F7%F2%EE-%F2%EE+%E3%E4%E5-%F2%EE; expires=Thu, 29-Oct-2015 01:11:04 GMT; Max-Age=3600; path=/~rasmus/; domain=example.com; secure

Connection:Keep-Alive
Content-Length:55
Content-Type:text/html
Date:Thu, 29 Oct 2015 00:10:19 GMT
Keep-Alive:timeout=5, max=100
Server:Apache/2.4.9 (Win32) mod_fcgid/2.3.9 PHP/5.5.12
Set-Cookie:TestCookie=%F7%F2%EE-%F2%EE+%E3%E4%E5-%F2%EE
Set-Cookie:TestCookie=%F7%F2%EE-%F2%EE+%E3%E4%E5-%F2%EE; expires=Thu, 29-Oct-2015 01:10:19 GMT; Max-Age=3600
Set-Cookie:TestCookie=%F7%F2%EE-%F2%EE+%E3%E4%E5-%F2%EE; expires=Thu, 29-Oct-2015 01:10:19 GMT; Max-Age=3600; path=/~rasmus/; domain=example.com; secure

**Comment by GunGraveKoga** [comment]
I solved this problem by formatting JSON-Array string:

static id lastkey = nil;

		if (([serverHeaders objectForKey:key]) == nil) {
			[serverHeaders setObject: value
				  	forKey: key];

			if (lastkey != nil) {
				[serverHeaders setObject:[[serverHeaders objectForKey:lastkey] stringByAppendingString:@"]"] 
					forKey:lastkey];
				[lastkey release];
				lastkey = nil;
			}
		}
		else {
			if (lastkey != nil)
				[serverHeaders setObject: [[serverHeaders objectForKey:key] stringByAppendingFormat:@",\"%@\"", value]
				  	forKey: key];
			else {
				[serverHeaders setObject:[OFString stringWithFormat:@"[\"%@\",\"%@\"", [serverHeaders objectForKey:key], value] 
					forKey:key];
				lastkey = [key retain];
			}
		}

But I don't know, is this solution is correct?

**Comment by Midar** [comment]
I'm not sure I understand your bug report. Are you trying to have multiple Set-Cookie fields? According to RFC 2616, repeating a header field is equivalent to having a comma-separated list:

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded.

Or do you mean that having the same field multiple times form the client does not create a comma-separated list? This would indeed be a missing feature.

**Comment by Midar** [comment]
As an aside: Your JSON solution seems very wrong to me, as it does manual string construction without proper escaping instead of using the JSON functionality of ObjFW.

**Comment by GunGraveKoga** [comment]
>>Or do you mean that having the same field multiple times form the client does not create a comma-separated list? This would indeed be a missing feature.
No, I mean that when OFHTTPClient received same field multiple times form HTTP Server, like Apache, HTTPClient rewrites value for specified key in OFHTTPResponse header dictionary.

**Comment by GunGraveKoga** [comment]
In my example I use multiple Set-Cookie with the same cookie name, this is incorrect like said in RFC 6265, but what about multiple Set-Cookie with different names? In current OFHTTPClient implementation our client gets only last of the all Set-Cookie directives

**Comment by Midar** [comment]
Ah, I thought you were talking about OFHTTPServer.

Yes, it should not replace it, but instead concatenate it, that's true.

**Comment by Midar** [comment]
Repeated fields are not concatenated (committed to master and 0.8 branch).
