### ISSUE TITLE
OFString::stringByStandardizingURLPath add support of file URI scheme

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#19]
"file URI scheme" (https://en.wikipedia.org/wiki/File_URI_scheme) ("file:///C:/Users" or "file:///usr/admin") a valid entry form for path string (file system and smb) in Unix OS and Windows OS

https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/

If OFString class will be able to return "file:///C:/Users" from "C:\Users" or "file://host/" from "\\host\" and will be able to create OS path string from "file:///" URL vise versa, it will be awesome.

**Comment by GunGraveKoga** [comment]
Sorry, I thought one more time, and sugess that we need use an other function for creating System Path URL.

**Comment by Midar** [comment]
I'm confused: If you have a file:// path, it should work with stringByStandardizingURLPath. If you have a local path (e.g. C:\Windows), you should use stringByStandardizingPath.

**Comment by GunGraveKoga** [comment]
Yes, I thought about something like [NSURL fileURLWithPath:(NSString *)pathToFile]

**Comment by Midar** [comment]
I see, you want to convert a native path to a URL. Not entirely sure where I would need that, but sure, let's add it :).

**Comment by Midar** [comment]
Added.

**Comment by GunGraveKoga** [comment]
Thanks
