### ISSUE TITLE
Why OFString::stringByStandardizingURLPath use componentsSeparatedByString: @"/" instead pathComponents?

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#22]
As result this method cannot convert string like @"base/url/path\example" to @"base/url/path/example", but pathComponents method correctly separate Windows & Unix style path into path components

**Comment by Midar** [comment]
base/url/path\example is not a valid URL path as per https://tools.ietf.org/html/rfc3986#section-3.3

**Comment by GunGraveKoga** [comment]
OK, I understood method functionality, name of method introduced me astray.
I just tried use something like this [[OFString pathWithComponents: @[[someurl path], @"path1", @"path2"]] stringByStandardizingURLPath] and got not what I expect.

Mea culpa
