### ISSUE TITLE
OFApplication: Double call of OF_setArgumentCount method on Win32.

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#23]
In OFApplication.m at function of_application_main (line 116) OFApplication shared instance call:
    [app OF_setArgumentCount: argc andArgumentValues: argv];
but then, on Win32 [app OF_setArgumentCount: wargc andWideArgumentValues: wargv]; was called

**Comment by Midar** [comment]
Please look carefully: Those are different functions and different variables. It stores the Unicode and the ASCII version, as some libs require one and others require the other.
