### ISSUE TITLE
Incorrect URL Encoding of cyrillic strings

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#25]
URL Encoding of cyrillic (and I suppose that all non latin) characters work incorrect

Original: мой файл
Encoded: %40%2C%40%2E%40%29%20%41%/4%40%20%40%29%40%2B

When I try to URL decode this string I get exception A format is invalid!

Short code:

```
#import <ObjFW/ObjFW.h>

int main(int argc, char const *argv[])
{
	OFString* cyrillic = @"мой файл";
	OFString* encoded = [cyrillic stringByURLEncoding];
	of_log(@"Original %@", cyrillic);
	of_log(@"Encoded %@", encoded);
	of_log(@"Decoded %@", [encoded stringByURLDecoding]); //Invalid format exception there
	return 0;
}
```

**Comment by Midar** [comment]
Thanks for reporting. This happens when char is a signed type: The shift operation is then a signed shift, while it should be an unsigned shift. Fixed by adding an intermediate variable that is unsigned char.
