### ISSUE TITLE
[OFTLSSocket] incorrect "delegate" property type

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#28]
In OFTLSSocket.h delegate property declared as `@property OF_NULLABLE_PROPERTY (assign) id <OFTLSSocket> delegate;` instead `@property OF_NULLABLE_PROPERTY (assign) id <OFTLSSocketDelegate> delegate;`

**Comment by Midar** [comment]
Thanks for spotting! Fixed!

I edited your bug report to properly show code - without it, it would remove everything between `<` and `>`, which made this very confusing :).

**Comment by GunGraveKoga** [comment]
Thanks, I just I forgot about this behavior of GitHub
