### ISSUE TITLE
[Windows] OFDate does not support date represented by string 2039-12-31 23:59:59

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#29]
I think OFDate must use _mktime64() instead mktime()

**Comment by Midar** [comment]
Do you define `_USE_32BIT_TIME_T`? Because `mktime()` should be `_mktime64()` according to MSDN, unless you define `_USE_32BIT_TIME_T`.

Anyway, since this is assigning to an `of_time_interval_t` anyway, I guess always using `_mktime64()` is safe, as it will not be truncated to a `time_t`.

**Comment by Midar** [comment]
Changed.
