### ISSUE TITLE
OFTarArchiveEntry.m compilation error with Clang+MinGW for i686

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#30]
OFTarArchiveEntry.m:70:25: error: implicit conversion from 'unsigned long long' to 'size_t' (aka 'unsigned int') changes value from 18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]
                    header + 124, 12, UINT64_MAX);
                                      ^~~~~~~~~~
c:/mingw-w64/i686-4.9.2-posix-dwarf-rt_v3-rev1/mingw32/i686-w64-mingw32/include\stdint.h:89:20: note: expanded from macro 'UINT64_MAX'
#define UINT64_MAX 0xffffffffffffffffULL /* 18446744073709551615ULL */
                   ^~~~~~~~~~~~~~~~~~~~~
OFTarArchiveEntry.m:74:25: error: implicit conversion from 'unsigned long long' to 'size_t' (aka 'unsigned int') changes value from 18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]
                    header + 136, 12, UINTMAX_MAX)];
                                      ^~~~~~~~~~~
c:/mingw-w64/i686-4.9.2-posix-dwarf-rt_v3-rev1/mingw32/i686-w64-mingw32/include\stdint.h:138:21: note: expanded from macro 'UINTMAX_MAX'
#define UINTMAX_MAX UINT64_MAX
                    ^~~~~~~~~~
c:/mingw-w64/i686-4.9.2-posix-dwarf-rt_v3-rev1/mingw32/i686-w64-mingw32/include\stdint.h:89:20: note: expanded from macro 'UINT64_MAX'
#define UINT64_MAX 0xffffffffffffffffULL /* 18446744073709551615ULL */
                   ^~~~~~~~~~~~~~~~~~~~~
OFTarArchiveEntry.m:150:21: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
                            exactLength: _toRead];

**Comment by Midar** [comment]
Ah, size_t vs uintmax_t on 32 bit systems, yeah. Forgot to test that, thanks. Fixed.
