### ISSUE TITLE
GZIPArchive.m compilation error on MinGW

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#31]
GZIPArchive.m:36:21: error: use of undeclared identifier 'S_IRWXG'
        mode &= (S_IRWXU | S_IRWXG | S_IRWXO);
                           ^
GZIPArchive.m:36:31: error: use of undeclared identifier 'S_IRWXO'
        mode &= (S_IRWXU | S_IRWXG | S_IRWXO);

Windows has chmod but does not support S_IRWXG and S_IRWXO modes

**Comment by Midar** [comment]
GZIPArchive.m was missing the same defines that already were in ZIPArchive.m. I moved those to OFZIP.h now to avoid having those defines in every .m file.

Interestingly, it built for me with MinGW-w64, so I guess they have recently added those. I remember having to add these defines to ZIPArchive.m before to make MinGW-w64 work.

BTW, for these small things, you can also just show up in #objfw on irc.freenode.net and tell me about it so I can quickly fix them :).
