### ISSUE TITLE
[Question] Create objc classes at runtime

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#34]
Apple ObjC runtime has ability to create classes and methods for those classes at runtime.
Does ObjFW runtime has this functionality?
If answer is No, then will be this functionality implemented in future?

**Comment by Midar** [comment]
Yes, it is possible, but not really convenient. Might be worth making this more convenient :). So let's make this a feature request.

**Comment by GunGraveKoga** [comment]
I think this opportunity would be very useful

**Comment by Midar** [comment]
I added objc_{allocate,register}ClassPair now. Additionally, I added class_addMethod() which did not exist before as class_replaceMethod() had the same functionality.

I need to look into adding ivars at runtime - I'm not sure how useful and/or fragile that is, though.
