### ISSUE TITLE
OFFileManager does not recognise drive letter on Win32

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#38]
Method createDirectoryAtPath:createParents: try to create path component that actually is a drive letter (C: D: E: etc)
directoryExistsAtPath: used inside the method does not return true for drive letters, because drive letters are not directories

```objc
#import <ObjFW/ObjFW.h>

int main(int argc, char const *argv[])
{
	OFString* path = @"C:\\test_folder\\test_subfolder";

	[[OFFileManager defaultManager] createDirectoryAtPath:path createParents:true]; //exception Failed to create directory C:: File exists

	return 0;
}
```

P.S. This is old bug, but I forgot to report it

**Comment by Midar** [comment]
`-[pathComponents]` now considers the drive letter to be part of the first component. This should fix `-[createDirectoryAtPath:]` for absolute paths on Windows.
