### ISSUE TITLE
macOS 10.12 deprecates NSStartSearchPathEnumeration for sysdir_start_search_path_enumeration 

### ISSUE THREAD

**Issue by The-Wolf312** [Midar/objfw#42]
I know there may not be support yet but opening the project after a failed build yields several Lexicon errors.
`The following build commands failed:
	CompileC build/ObjFW.build/Release/ObjFW.build/Objects-normal/x86_64/OFSystemInfo.o src/OFSystemInfo.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	Ld build/Release/ObjFW.framework/Versions/A/ObjFW normal x86_64
(2 failures)
`

**Comment by Midar** [comment]
Unfortunately, your paste does not contain the real error. As I do not have the Sierra beta, can you please paste the *full* log?

Additionally, can you please try if it works with the make-based build system? Just do a clean clone (this is important to make sure there are not leftovers from xcodebuild) and run `autoreconf && ./configure && make`.

**Comment by The-Wolf312** [comment]
I currently do not have a log available however I tried the ./configure method first and it failed as well.

**Comment by Midar** [comment]
Thanks. So it seems Apple has deprecated NSStartSearchPathEnumeration and replaced it with sysdir_start_search_path_enumeration. Unfortunately, there does not seem to be any public documentation yet (0 results on Google), so I cannot add a configure check and use it instead on 10.12 instead.

Can you add -Wno-error=deprecated-declarations to OBJCFLAGS and try again? It should work then. Once I can look at 10.12 documentation, I can add a configure check for this (I suppose you cannot even tell me the interface, as I suppose you had to sign an NDA).

**Comment by Midar** [comment]
It seems the Xcode beta is available after signup, as is the macOS Sierra beta.

**Comment by Midar** [comment]
Ok, finally got the update installed now. On macOS 10.12, sysdir_start_search_path_enumeration() is used now.

**Comment by The-Wolf312** [comment]
I'll try the flags. Hopefully that works well, good luck with the public beta.

**Comment by Midar** [comment]
No need to try the flags. On macOS 10.12, sysdir_start_search_path_enumeration() is used now.
