### ISSUE TITLE
invalid checking of 'count' argument in -[OFDataArray addItems: count:]

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#43]
Expression 
``` с
if (count > SIZE_MAX - count)
```
has no sense

in some cases, if value of "count" argument passed in addItems:count: in excess of (SIZE_MAX / 2) + 1, exception OFOutOfRangeException always will be throwed

**Comment by Midar** [comment]
There's indeed an underscore missing - thanks for pointing it out! Fixed.
