### ISSUE TITLE
Implement cookie handling in OFHTTPClient and OFHTTPServer

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#45]
When OFHTTPClient sends OFHTTPRequest and OFHTTPServer takes OFHTTPRequest and makes response with OFHTTPRespose, Cookies property of Request/Respons are ignored

**Comment by Midar** [comment]
This is because OFHTTPClient does not implement cookies yet. It's on the TODO list.

**Comment by Midar** [comment]
Cookies are not special anymore now, and are just part of the headers. There are now convenience methods to parse headers to cookies and generate headers for cookies, therefore I'm closing this now. If this does not satisfy your requirements, please reopen!
