### ISSUE TITLE
OFHTTPServer sets invalid "path" property for OFHTTPRequest`s OFURL-property

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#50]
https://github.com/Midar/objfw/blob/master/src/OFHTTPServer.m#L476

"/" prefix of URL path always will be cuts out for incoming requests/
As result "string" method of OFURL instance alway will throws OFInvalidFormatException

**Comment by Midar** [comment]
Ah, thanks. This was overlooked when it was changed that the URL should contain the /. Fixed.
