### ISSUE TITLE
OFProperty cannot parse attributes of synthesised property with Apple runtime

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#53]
In Apple runtime property attributes contains ivar name but of_initWithProperty: method does not know about it and raise exception from ```switch (*attributes)```

For example in my test class I have property named prop and synthesised as prop=_prop
resulting property attributes string will be "T@\"OFString\",C,N,V_prop"

But token 'V' does not handled in switch statement

**Comment by Midar** [comment]
Thanks for reporting! Fixed.
